### ISSUE TITLE
Can't build with XCode 9.2, got error "Too many arguments to block call, expected 1, have 3"

### ISSUE THREAD

**Issue by 0xhakawai** [inProgress-team/react-native-youtube#246]
Hi, I got an error "**Too many arguments to block call, expected 1, have 3**" after updating to **XCode 9.2**
At 'RCTYoutubeStandalone.m' at line

`reject(@“error”, @“XCDYouTubeKit is not installed”, nil);`

react-native: 0.50.4
react-native-youtube: ^1.0.1

Does anyone know how to fix it ? Please help me

**Comment by davidohayon669** [comment]
@saly2310 can you build the example app in this repo?

**Comment by dann1609** [comment]
add:
 `pod 'XCDYouTubeKit', '~> 2.5'` to pod file and run pod install

**Comment by luisfuertes** [comment]
+1

**Comment by khoa90it** [comment]
I have same issue @luisfuertes

**Comment by jeiemgi** [comment]
Hi, have the same error, were you able to fix it?

**Comment by engladgut** [comment]
![image](https://user-images.githubusercontent.com/4556846/46593424-d8a90d00-cb06-11e8-968e-7af1566843d1.png)

I added 'libXCDYouTubeKit.a' manually to 'My Target > Build Phases > Link Binary With Libraries' list then it works fine. I don't know why but the library is in pods and builds well but it doesn't work before setting it manually.

Anyways hope it helps someone.

**Comment by lefrankleal** [comment]
> xcode : 10
> react : 16.4.2
> react-native : 0.55.4
> 
> ![image](https://user-images.githubusercontent.com/4556846/46593424-d8a90d00-cb06-11e8-968e-7af1566843d1.png)
> 
> I added 'libXCDYouTubeKit.a' manually to 'My Target > Build Phases > Link Binary With Libraries' list then it works fine. I don't know why but the library is in pods and builds well but it doesn't work before setting it manually.
> 
> Anyways hope it helps someone.

where is this .a file located?

**Comment by zabojad** [comment]
The right way to do this is in [README](https://github.com/davidohayon669/react-native-youtube#setup):

> Standalone iOS player Uses XCDYoutubeKit (Warning: XCDYoutubeKit doesn't conform to YouTube's Terms Of Use). Add the next line to your Podfile and run pod install inside /ios folder:
> 
> pod 'XCDYouTubeKit', '~> 2.8'
