### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by krapspark** [inProgress-team/react-native-youtube#53]
Hi,

I just checked out the repo and tried to run through the example.
The first `npm install` finishes OK.
But when I open the Xcode project and try to run it webserver complains about missing dependencies.
So I tried `npm install` again and I got bunch of compilation errors the second time around.

Here are the first few errors:

>   CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^

Any idea on how I can fix this?
Thank you.

**Comment by erikdung** [comment]
Cannot build example!!
![image](https://cloud.githubusercontent.com/assets/5372121/16195461/f55b2b3e-36f9-11e6-8a67-1e04f8664f17.png)
Please help

**Comment by burnsting** [comment]
Should this still work with RN 0.28? I'm getting a render error when adding the <Youtube /> component. It used to work fine.

> "Element type is invalid expected a string (for built-in components) or a class/function. Check the render method of ..."
